<!DOCTYPE html>
<html>

<?php
session_start();
ini_set('include_path', 'jpgraph');
	session_cache_expire( 20 );
$inactive = 1200;
if(isset($_SESSION['start']) ) {
	$session_life = time() - $_SESSION['start'];
	if($session_life > $inactive){
		echo "<script>alert('Session Timeout! Please Login Again!');</script>";
		echo "<script>self.location='../welcome.php'</script>";
	}
}
$_SESSION['start'] = time();





if(!isset($_SESSION['username']))
    {
      echo "<script>alert('You are not logged in!');</script>";
		  echo "<script>self.location='../welcome.php'</script>";
      } 

include("connect.php");
include("html_to_doc.inc.php");
if(isset($_REQUEST['go2'])){

$subject = $_REQUEST['subject'];
$eval= $_REQUEST['eval'];
$_SESSION['subject']=$subject;

$_SESSION['eval']=$eval;






echo " <nav>
	     <div class='nav-wrapper blue'>
         <div class='row'>
           <div class='col s8 offset-s1'>
              <a href='#'>Question Paper Generator</a>
           </div>
           <div col='col s4'>
              <a href='#' class='offset-s8'> Logged in as ";echo $_SESSION["username"]; echo"</a>
          </div>
        </div>
   </nav>

 <div class='row'>
    <div class='col s12 blue'>
      <ul class='tabs white'>
        <li class='tab col s3 blue'><a class='active white-text' href='#test1'>Home</a></li>
        <li class='tab col s3 blue'><a class='active white-text' href='#test2'>Developers</a></li>
        <li class='tab col s3 blue' ><a class='active white-text' href='#test3'>Guidelines</a></li>
        <li class='tab col s3 blue'><a class='active white-text' href='#test4'>About Us</a></li>
        <div class='indicator white' style='z-index:1' </div>
      </ul>
    </div>
  </div>

";





$result = mysql_query("SELECT * FROM Question_Paper where Course_ID = '$subject' and Eval_ID='$eval'");

if(!$result or $result==null){
	echo "<script>alert('Error : No Question Papers Found');</script>";

}

else{
echo "<center><table class='bordered highlight'>
       <thead>
         <tr>
             <th>Generated by</th>
             <th>ID</th>
             <th>L1 Questions</th>
             <th>L2 Questions</th>
             <th>L3 Questions</th></thead>
         </tr>";


       $options='';
       $width = 600; $height = 200;
       while($row = mysql_fetch_array($result))
       {
       $f=$row['QP_ID'];
       $l1=$row['L1'];
       $l2=$row['L2'];
       $l3=$row['L3'];

         echo "<tr>";
         echo "<td>". $row['S_ID'] ."</td>";
         echo "<td>". $row['QP_ID'] ."</td>";
         echo "<td>". $row['L1'] ."</td>";
         echo "<td>". $row['L2'] . "</td>";
         echo "<td>". $row['L3'] ."</td>";
         echo "</tr>";

	$options.="<OPTION VALUE=\"$f\">".$f."</OPTION>";
       }
     echo"</table></center>";

mysql_close($con);


}
}
?>

<head>

          <meta charset="UTF-8">
          <title>Display question papers</title>
          <!--Import Google Icon Font-->
          <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          <!--Import materialize.css-->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
          <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
          <script>
            $(document).ready(function() {
            $('select').material_select();
            $(".button-collapse").sideNav();
          });
          </script>
          <!--Let browser know website is optimized for mobile-->
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>


<body>






<div>

 <div class="container">
 <div class = "row">
  <h4 align="center" class="grey-text"></h4>
<center>
		<form class="form" method="post" action="renderqp.php">
         <div class="input-field col s3">
			<select name="qps">
				<option value="" disabled selected>Choose QP</option>
				<?php echo($options);?>
			</select>

</div>

         <div class="input-field col s6 offset-s3">
	          <button class="waves-effect waves-light btn blue" name="display"  type="submit">
            Display</button>
	       </div>



 <div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large blue hoverable" href="admindash.php">
      <i class="material-icons right">send</i>
    </a>
    </div>
          <br><br>
		</form>

<br><br>
</div>
</div></div>



  </body>
</html>
